puddle/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('', views.inbox, name='inbox'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

puddle/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name="contact"),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout')
]

puddle/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

puddle/item/urls.py
from django.urls import path

from . import views

# namespace
app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
]

puddle/puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    #all url starting with item will go to the item namespace url
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
     path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'input'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'input'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'input'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'input'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'input'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'input'
    }))

puddle/core/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import logout
from item.models import Category, Item
from .forms import SignupForm


def index(req):
    items = Item.objects.filter(is_sold=False).order_by('-created_at')[0:9]
    categories = Category.objects.all()
    return render(req, 'core/index.html', {
        'categories': categories,
        'items': items,
    })


def contact(req):
    return render(req, 'core/contact.html')


def signup(req):
    if req.method == 'POST':
        form = SignupForm(req.POST)
        if form.is_valid():
            form.save()

            return redirect('/login')
    else:
        form = SignupForm()
    return render(req, 'core/signup.html', {
        'form': form
    })

def logout_view(req):
    logout(req)
    return redirect('core:index')

puddle/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %}{% endblock %} | GatheringHub</title>
	<link rel="stylesheet" href="{% static 'main.css' %}">
	<link rel="stylesheet" href="{% static 'front.css' %}">
	{%block styles %}
	{% endblock%}
</head>

<body>
	<header>
		<nav>
			<a href="/">GatheringHub</a>
			<div id="nav-menu">
				<a href="{% url 'item:new' %}" class="nav-item">New Item</a>
				<a href="{% url 'item:items' %}" class="nav-item">Browser</a>
				{% if request.user.is_authenticated %}
				<a href="{% url 'conversation:inbox' %}" class="session-btn-1">Inbox</a>
				<a href="{% url 'dashboard:index' %}" class="session-btn-2">Dashboard</a>
				<a href="{% url 'core:logout' %}" class="session-btn-2">Logout</a>
				{% else %}
				<a href="{% url 'core:signup' %}" class="session-btn-1">Sign Up</a>
				<a href="{% url 'core:login' %}" class="session-btn-2">Log in</a>
				{% endif %}
			</div>
		</nav>
	</header>
	<div>
		{% block content %}
		{% endblock %}
	</div>
	<footer>
		<div>
			<h3>About</h3>
			<p>GH is the most popular hunter's goods marketplace.</p>
		</div>

		<div>
			<h3>Menu</h3>
			<ul>
				<li><a href="#" class="list-item">About</a></li>
				<li><a href="{% url 'core:contact' %}" class="list-item">Contact</a></li>
				<li><a href="#" class="list-item">Privacy Policy</a></li>
				<li><a href="#" class="list-item">Term of use</a></li>
			</ul>
		</div>
	</footer>
</body>

</html>

puddle/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
<h1 class="front-title">Contact Page</h1>
{% endblock %}

puddle/core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %}Welcome{% endblock %}

{% block content %}
	<div class="items">
		<h2>Newest Items</h2>

		<div class="item-list">
			{% for item in items %}
				<div class="grid-item">
					<a href="{% url 'item:detail' item.id %}" >
						<div class="img-container">
							<img src="{{ item.image.url }}" />
						</div>

						<div class="item-info">
							<h2>{{ item.name }}</h2>
							<p>Price: {{ item.price }} zenny</p>
						</div>
					</a>
				</div>
			{% endfor %}
		</div>
	</div>

	<div class="items">
		<h2>Categories</h2>

		<div class="item-list">
			{% for category in categories %}
				<div class="grid-item">
					<a href="#" >
						<div class="item-info">
							<h2>{{ category.name }}</h2>
							<p>{{ category.items.count }} items </p>
						</div>
					</a>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

puddle/core/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}
{%block styles %}
<link rel="stylesheet" href="{% static 'form.css' %}">
{% endblock %}
{% block title %}Log in{% endblock %}

{% block content %}
<div class="form-container">
	<h1>Log In</h1>

	<form action="." method="post">
		{% csrf_token %}
		<div>
			<label>Username</label><br>
			{{ form.username }}
		</div>

		<div>
			<label>Password</label><br>
			{{ form.password }}
		</div>


		{% if form.errors or form.non_field_errors %}
		<div class="error-msg">
			{% for field in form %}
			{{ field.errors }}
			{% endfor %}

			{{ form.non_field_errors }}
		</div>
		{% endif %}


		<button>Submit</button>
	</form>
</div>
{% endblock content %}

puddle/core/templates/core/signup.html
{% extends 'core/base.html' %}
{% load static %}
{%block styles %}
<link rel="stylesheet" href="{% static 'signup.css' %}">
{% endblock %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="form-container">
	<h1>SignUp</h1>

	<form action="." method="post">
		{% csrf_token %}
		<div>
			<label>Username</label><br>
			{{ form.username }}
		</div>

		<div>
			<label>Email</label><br>
			{{ form.email }}
		</div>

		<div>
			<label>Password</label><br>
			{{ form.password1 }}
		</div>

		<div>
			<label>Repeat password</label><br>
			{{ form.password2 }}
		</div>

		{% if form.errors or form.non_field_errors %}
		<div class="error-msg">
			{% for field in form %}
			{{ field.errors }}
			{% endfor %}

			{{ form.non_field_errors }}
		</div>
		{% endif %}


		<button>Submit</button>
	</form>
</div>
{% endblock content %}