puddle/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('', views.inbox, name='inbox'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

puddle/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name="contact"),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout')
]

puddle/item/urls.py
from django.urls import path

from . import views

# namespace
app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
]

puddle/puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    #all url starting with item will go to the item namespace url
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
     path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

puddle/item/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category,related_name="items", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.name

puddle/item/forms.py
from django import forms

from .models import Item


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image')
        widgets = {
            'category': forms.Select(attrs={'class': 'input'}),
            'name': forms.TextInput(attrs={
                'class': 'input'
            }),
            'description': forms.Textarea(attrs={
                'class': 'input'
            }),
            'price': forms.TextInput(attrs={
                'class': 'input'
            }),
            'image': forms.FileInput(attrs={
                'class': 'input'
            })
        }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'input'
            }),
            'description': forms.Textarea(attrs={
                'class': 'input'
            }),
            'price': forms.TextInput(attrs={
                'class': 'input'
            }),
            'image': forms.FileInput(attrs={
                'class': 'input'
            })
        }

puddle/item/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from .models import Category, Item
from .forms import EditItemForm, NewItemForm


def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(
        category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })


@login_required
def new(req):
    if req.method == 'POST':
        form = NewItemForm(req.POST, req.FILES)
        if form.is_valid():
            # commit = false for creating an object but not saving in the DB
            item = form.save(commit=False)
            item.created_by = req.user
            item.save()
            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()
    return render(req, 'item/form.html', {
        'form': form,
        'title': 'New item',
    })


@login_required
def edit(req, pk):
    item = get_object_or_404(Item, pk=pk, created_by=req.user)
    if req.method == 'POST':
        form = EditItemForm(req.POST, req.FILES, instance=item)
        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(req, 'item/editform.html', {
        'pk': pk,
        'form': form,
        'title': 'Edit item',
    })


@login_required
def delete(req, pk):
    item = get_object_or_404(Item, pk=pk, created_by=req.user)
    item.delete()
    return redirect('dashboard:index')

puddle/item/templates/item/detail.html
{% extends "core/base.html" %}
{% load static %}
{%block styles %}
<link rel="stylesheet" href="{% static 'detail.css' %}">
{% endblock %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div id="details-container">
    <div>
        <img src="{{ item.image.url }}">
    </div>

    <div>
        <h1>{{ item.name }}</h1>
        <p><strong>Price: </strong>{{ item.price }}</p>
        <p><strong>Seller: </strong>{{ item.created_by.username }}</p>

        {% if item.description %}
        <p class="item-description">
            <strong class="text-gray-500">Description:</strong><br>
            {{ item.description }}
        </p>
        {% endif %}

        
        {% if request.user == item.created_by %}
        <div id='update-delete-container'>
            <p>This is your item!</p>
            <a href="{% url 'item:edit' item.id %}"
            class="session-btn-1">Edit</a>
            <a href="{% url 'item:delete' item.id %}"
            class="session-btn-2">Delete</a>
        </div>
        {% else %}
        <a href="{% url 'conversation:new' item.id %}" class="session-btn-1">Contact
        seller</a>
        {% endif %}
    </div>
</div>
<div class="items">
    <h2>Related Items</h2>

    <div class="item-list">
        {% for item in related_items %}
        <div class="grid-item">
            <a href="{% url 'item:detail' item.id %}">
                <div class="img-container">
                    <img src="{{ item.image.url }}" />
                </div>

                <div class="item-info">
                    <h2>{{ item.name }}</h2>
                    <p>Price: {{ item.price }} zenny</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

puddle/item/templates/item/editform.html
{% extends 'core/base.html' %}
{% load static %}
{%block styles %}
<link rel="stylesheet" href="{% static 'form.css' %}">
{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 id="add-title">Edit an Item</h1>

<form method="post" action="{% url 'item:edit' pk %}" enctype="multipart/form-data">
    {% csrf_token %}

    <div>
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
	<button>Submit</button>
</form>
{% endblock %}

puddle/item/templates/item/form.html
{% extends 'core/base.html' %}
{% load static %}
{%block styles %}
<link rel="stylesheet" href="{% static 'form.css' %}">
{% endblock %}
{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 id="add-title">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div>
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
	<button>Submit</button>
</form>
{% endblock %}

puddle/item/templates/item/items.html
{% extends 'core/base.html' %}
{% load static %}
{%block styles %}
<link rel="stylesheet" href="{% static 'items.css' %}">
{% endblock %}
{% block title %}Items{% endblock %}

{% block content %}
<div id="items-container">
	<div>
		<form method="get" action="{% url 'item:items' %}">
			<input name="query" type="text" value="{{ query }}" placeholder="Find any stuff...">

			<button>Search</button>
		</form>

		<p>Categories</p>

		<ul>
			{% for category in categories %}
			<li class="{% if category.id == category_id %} same-category {% endif %}">
				<a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
			</li>
			{% endfor %}
		</ul>

		<p class="font-semibold">Clear filters</p>

		<ul>
         <li><a href="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>
	</div>
	<div>
		<div class="item-list">
			{% for item in items %}
			<div class="grid-item">
				<a href="{% url 'item:detail' item.id %}">
					<div class="img-container">
						<img src="{{ item.image.url }}" />
					</div>

					<div class="item-info">
						<h2>{{ item.name }}</h2>
						<p>Price: {{ item.price }} zenny</p>
					</div>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>
</div>
{% endblock content %}